[package]
name = "sandbox-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
wgpu = "27.0.1"
# winit = "0.30.12"

[dependencies.sdl3]
version = "0.15.1"
features = ["raw-window-handle"]
